### ISSUE TITLE
Add dependencies for SINA build/run to conda

### ISSUE THREAD

**Issue by epruesse** [epruesse/SINA#8]
Building SINA requires ARB, which in turn requires a bunch of other libraries not currently in bioconda or conda-forge to be packaged first. 

- [x] ARB bioconda/bioconda-recipes#4952
  - [x] openmotif conda-forge/staged-recipes#2582
    - [x] xorg-xbitmaps conda-forge/staged-recipes#2604
    - [x] xorg-libxp conda-forge/staged-recipes#2607
       - [x] xorg-printproto conda-forge/staged-recipes#2594
  - [x] fig2dev conda-forge/staged-recipes#2650
  - [x] xfig conda-forge/staged-recipes#2651
  - [x] xorg-xft conda-forge/staged-recipes#2592
  - [x] xorg-makedepend conda-forge/staged-recipes#2606
  - [x] time conda-forge/staged-recipes#3139
  - [x] lynx conda-forge/staged-recipes#3123
    - [x] libidb11 conda-forge/staged-recipes#3126
  - [x] PhyML bioconda/bioconda-recipes#5033
  - [x] MrBayes bioconda/bioconda-recipes#5024
